version: "3"
services:
    postgres:
        image: postgres:11.5
        container_name: postgres_master_api
        restart: always
        environment:
            POSTGRES_PASSWORD: masterapi
        ports:
            - 5432:5432
    redis:
        image: redis:latest
        container_name: redis_master_api
        restart: always
        command: ["redis-server", "--bind", "redis", "--port", "6379"]
        ports:
            - 6379:6379

